import 'bloc/notification_settings_bloc.dart';import 'models/notification_settings_model.dart';import 'package:clean_egypt/core/app_export.dart';import 'package:clean_egypt/widgets/app_bar/appbar_leading_iconbutton_one.dart';import 'package:clean_egypt/widgets/app_bar/appbar_subtitle_one.dart';import 'package:clean_egypt/widgets/app_bar/custom_app_bar.dart';import 'package:clean_egypt/widgets/custom_elevated_button.dart';import 'package:clean_egypt/widgets/custom_switch.dart';import 'package:flutter/material.dart';class NotificationSettingsScreen extends StatelessWidget {const NotificationSettingsScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<NotificationSettingsBloc>(create: (context) => NotificationSettingsBloc(NotificationSettingsState(notificationSettingsModelObj: NotificationSettingsModel()))..add(NotificationSettingsInitialEvent()), child: NotificationSettingsScreen()); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 22.h, vertical: 46.v), child: Column(children: [Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 7.h), child: Text("lbl_reminder_habit".tr, style: CustomTextStyles.headlineSmallPrimaryContainer))), SizedBox(height: 23.v), _buildSoundRow(context), SizedBox(height: 48.v), _buildNinetyEightRow(context), SizedBox(height: 51.v), _buildCouponsRow(context), SizedBox(height: 45.v), _buildVibrateRow(context), SizedBox(height: 51.v), _buildAppUpdatesRow(context), Spacer(), SizedBox(height: 14.v), CustomElevatedButton(text: "lbl_update_profile".tr, margin: EdgeInsets.symmetric(horizontal: 3.h), buttonTextStyle: CustomTextStyles.titleMediumWhiteA7000118)])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 65.h, leading: AppbarLeadingIconbuttonOne(imagePath: ImageConstant.imgArrowLeftGray900, margin: EdgeInsets.only(left: 25.h, top: 8.v, bottom: 8.v), onTap: () {onTapArrowLeft(context);}), centerTitle: true, title: AppbarSubtitleOne(text: "lbl_notification".tr)); } 
/// Section Widget
Widget _buildSoundRow(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 7.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("lbl_sound".tr, style: CustomTextStyles.titleLargeBluegray90001), BlocSelector<NotificationSettingsBloc, NotificationSettingsState, bool?>(selector: (state) => state.isSelectedSwitch, builder: (context, isSelectedSwitch) {return CustomSwitch(margin: EdgeInsets.only(top: 2.v), value: isSelectedSwitch, onChange: (value) {context.read<NotificationSettingsBloc>().add(ChangeSwitchEvent(value: value));});})])); } 
/// Section Widget
Widget _buildNinetyEightRow(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 7.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("msg_order_notification".tr, style: CustomTextStyles.titleLargeBluegray90001), BlocSelector<NotificationSettingsBloc, NotificationSettingsState, bool?>(selector: (state) => state.isSelectedSwitch1, builder: (context, isSelectedSwitch1) {return CustomSwitch(margin: EdgeInsets.only(top: 2.v), value: isSelectedSwitch1, onChange: (value) {context.read<NotificationSettingsBloc>().add(ChangeSwitch1Event(value: value));});})])); } 
/// Section Widget
Widget _buildCouponsRow(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 7.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("lbl_coupons".tr, style: CustomTextStyles.titleLargeBluegray90001), BlocSelector<NotificationSettingsBloc, NotificationSettingsState, bool?>(selector: (state) => state.isSelectedSwitch2, builder: (context, isSelectedSwitch2) {return CustomSwitch(margin: EdgeInsets.only(bottom: 4.v), value: isSelectedSwitch2, onChange: (value) {context.read<NotificationSettingsBloc>().add(ChangeSwitch2Event(value: value));});})])); } 
/// Section Widget
Widget _buildVibrateRow(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 7.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("lbl_vibrate".tr, style: CustomTextStyles.titleLargeBluegray90001), BlocSelector<NotificationSettingsBloc, NotificationSettingsState, bool?>(selector: (state) => state.isSelectedSwitch3, builder: (context, isSelectedSwitch3) {return CustomSwitch(margin: EdgeInsets.only(top: 2.v), value: isSelectedSwitch3, onChange: (value) {context.read<NotificationSettingsBloc>().add(ChangeSwitch3Event(value: value));});})])); } 
/// Section Widget
Widget _buildAppUpdatesRow(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 7.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("lbl_app_updates".tr, style: CustomTextStyles.titleLargeBluegray90001), BlocSelector<NotificationSettingsBloc, NotificationSettingsState, bool?>(selector: (state) => state.isSelectedSwitch4, builder: (context, isSelectedSwitch4) {return CustomSwitch(margin: EdgeInsets.only(bottom: 4.v), value: isSelectedSwitch4, onChange: (value) {context.read<NotificationSettingsBloc>().add(ChangeSwitch4Event(value: value));});})])); } 

/// Navigates to the previous screen.
onTapArrowLeft(BuildContext context) { NavigatorService.goBack(); } 
 }
