import '../my_impact_screen/widgets/pinaddgrid_item_widget.dart';import 'bloc/my_impact_bloc.dart';import 'models/my_impact_model.dart';import 'models/pinaddgrid_item_model.dart';import 'package:clean_egypt/core/app_export.dart';import 'package:clean_egypt/widgets/app_bar/appbar_leading_iconbutton_one.dart';import 'package:clean_egypt/widgets/app_bar/appbar_subtitle_two.dart';import 'package:clean_egypt/widgets/app_bar/custom_app_bar.dart';import 'package:clean_egypt/widgets/custom_outlined_button.dart';import 'package:flutter/material.dart';class MyImpactScreen extends StatelessWidget {const MyImpactScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<MyImpactBloc>(create: (context) => MyImpactBloc(MyImpactState(myImpactModelObj: MyImpactModel()))..add(MyImpactInitialEvent()), child: MyImpactScreen()); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 47.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Container(width: 277.h, margin: EdgeInsets.only(left: 11.h, right: 56.h), child: RichText(text: TextSpan(children: [TextSpan(text: "lbl_yo".tr, style: CustomTextStyles.titleLargeBlack900), TextSpan(text: "msg_u_ve_been_an_clean".tr, style: CustomTextStyles.titleLargeBlack900Medium_1), TextSpan(text: "lbl_1".tr, style: CustomTextStyles.titleLargeGreen400), TextSpan(text: "lbl_day".tr, style: CustomTextStyles.titleLargeBlack900Medium_1)]), textAlign: TextAlign.left)), SizedBox(height: 20.v), Padding(padding: EdgeInsets.only(left: 11.h), child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_total_impact".tr, style: CustomTextStyles.titleMediumGreen400Medium), CustomImageView(imagePath: ImageConstant.imgProfileBlueGray10002, height: 18.adaptSize, width: 18.adaptSize, margin: EdgeInsets.only(left: 8.h, bottom: 5.v))])), SizedBox(height: 20.v), _buildPinAddGrid(context), Spacer(), Align(alignment: Alignment.center, child: Text("msg_pin_and_photo_for".tr, style: CustomTextStyles.titleSmallBluegray40001)), SizedBox(height: 17.v), CustomOutlinedButton(text: "msg_share_your_impact".tr, margin: EdgeInsets.only(left: 1.h), buttonStyle: CustomButtonStyles.outlineBlueGray, buttonTextStyle: CustomTextStyles.titleMediumBluegray600), SizedBox(height: 13.v)])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 65.h, leading: AppbarLeadingIconbuttonOne(imagePath: ImageConstant.imgArrowLeftGray900, margin: EdgeInsets.only(left: 25.h, top: 8.v, bottom: 8.v), onTap: () {onTapArrowLeft(context);}), centerTitle: true, title: AppbarSubtitleTwo(text: "lbl_my_impact".tr)); } 
/// Section Widget
Widget _buildPinAddGrid(BuildContext context) { return Align(alignment: Alignment.center, child: Padding(padding: EdgeInsets.only(left: 11.h, right: 8.h), child: BlocSelector<MyImpactBloc, MyImpactState, MyImpactModel?>(selector: (state) => state.myImpactModelObj, builder: (context, myImpactModelObj) {return GridView.builder(shrinkWrap: true, gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(mainAxisExtent: 77.v, crossAxisCount: 2, mainAxisSpacing: 24.h, crossAxisSpacing: 24.h), physics: NeverScrollableScrollPhysics(), itemCount: myImpactModelObj?.pinaddgridItemList.length ?? 0, itemBuilder: (context, index) {PinaddgridItemModel model = myImpactModelObj?.pinaddgridItemList[index] ?? PinaddgridItemModel(); return PinaddgridItemWidget(model);});}))); } 

/// Navigates to the previous screen.
onTapArrowLeft(BuildContext context) { NavigatorService.goBack(); } 
 }
