import 'bloc/add_manually_location_bloc.dart';import 'models/add_manually_location_model.dart';import 'package:clean_egypt/core/app_export.dart';import 'package:clean_egypt/widgets/custom_elevated_button.dart';import 'package:flutter/material.dart';class AddManuallyLocationScreen extends StatelessWidget {const AddManuallyLocationScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<AddManuallyLocationBloc>(create: (context) => AddManuallyLocationBloc(AddManuallyLocationState(addManuallyLocationModelObj: AddManuallyLocationModel()))..add(AddManuallyLocationInitialEvent()), child: AddManuallyLocationScreen()); } 
@override Widget build(BuildContext context) { return BlocBuilder<AddManuallyLocationBloc, AddManuallyLocationState>(builder: (context, state) {return SafeArea(child: Scaffold(body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 23.h), child: Column(mainAxisAlignment: MainAxisAlignment.center, children: [Container(height: 115.adaptSize, width: 115.adaptSize, padding: EdgeInsets.symmetric(horizontal: 35.h, vertical: 29.v), decoration: AppDecoration.fillGreen.copyWith(borderRadius: BorderRadiusStyle.roundedBorder58), child: CustomImageView(imagePath: ImageConstant.imgLinkedin, height: 56.v, width: 45.h, alignment: Alignment.center)), SizedBox(height: 36.v), Text("msg_what_is_your_location".tr, style: CustomTextStyles.headlineSmallBlack900), SizedBox(height: 9.v), Container(width: 253.h, margin: EdgeInsets.only(left: 45.h, right: 48.h), child: Text("msg_we_need_to_know".tr, maxLines: 2, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: CustomTextStyles.labelLargeGray70001SemiBold)), SizedBox(height: 23.v), CustomElevatedButton(text: "msg_allow_location_access".tr, onPressed: () {onTapAllowLocationAccess(context);}), SizedBox(height: 28.v), GestureDetector(onTap: () {onTapTxtEnterLocationManually(context);}, child: Text("msg_enter_location_manually".tr, style: CustomTextStyles.titleMediumBluegray500)), SizedBox(height: 5.v)]))));}); } 
/// Navigates to the mapPinScreen when the action is triggered.
onTapAllowLocationAccess(BuildContext context) { NavigatorService.pushNamed(AppRoutes.mapPinScreen, ); } 
/// Navigates to the locationAccessScreen when the action is triggered.
onTapTxtEnterLocationManually(BuildContext context) { NavigatorService.pushNamed(AppRoutes.locationAccessScreen, ); } 
 }
