import 'bloc/complete_your_profile_bloc.dart';import 'models/complete_your_profile_model.dart';import 'package:clean_egypt/core/app_export.dart';import 'package:clean_egypt/widgets/app_bar/appbar_leading_iconbutton_one.dart';import 'package:clean_egypt/widgets/app_bar/custom_app_bar.dart';import 'package:clean_egypt/widgets/custom_drop_down.dart';import 'package:clean_egypt/widgets/custom_elevated_button.dart';import 'package:clean_egypt/widgets/custom_outlined_button.dart';import 'package:clean_egypt/widgets/custom_phone_number.dart';import 'package:clean_egypt/widgets/custom_text_form_field.dart';import 'package:country_pickers/country.dart';import 'package:country_pickers/country_pickers.dart';import 'package:flutter/material.dart';
// ignore_for_file: must_be_immutable
class CompleteYourProfileScreen extends StatelessWidget {CompleteYourProfileScreen({Key? key}) : super(key: key);

GlobalKey<FormState> _formKey = GlobalKey<FormState>();

static Widget builder(BuildContext context) { return BlocProvider<CompleteYourProfileBloc>(create: (context) => CompleteYourProfileBloc(CompleteYourProfileState(completeYourProfileModelObj: CompleteYourProfileModel()))..add(CompleteYourProfileInitialEvent()), child: CompleteYourProfileScreen()); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: Form(key: _formKey, child: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 23.h, vertical: 19.v), child: Column(children: [Text("msg_complete_your_profile".tr, style: theme.textTheme.titleMedium), SizedBox(height: 20.v), Container(width: 301.h, margin: EdgeInsets.only(left: 22.h, right: 23.h), child: Text("msg_don_t_worry_only".tr, maxLines: 2, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: CustomTextStyles.bodyMediumGray70001)), SizedBox(height: 5.v), CustomImageView(imagePath: ImageConstant.imgProfileGray30001, height: 118.v, width: 116.h), SizedBox(height: 6.v), _buildName(context), SizedBox(height: 14.v), _buildPhoneNumber(context), SizedBox(height: 14.v), _buildGender(context), SizedBox(height: 14.v), _buildAlexandria(context), SizedBox(height: 81.v), CustomElevatedButton(text: "msg_complete_profile".tr, onPressed: () {onTapCompleteProfile(context);}), SizedBox(height: 5.v)]))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: double.maxFinite, leading: AppbarLeadingIconbuttonOne(imagePath: ImageConstant.imgArrowLeftGray900, margin: EdgeInsets.fromLTRB(26.h, 8.v, 327.h, 8.v), onTap: () {onTapArrowLeft(context);})); } 
/// Section Widget
Widget _buildName(BuildContext context) { return Padding(padding: EdgeInsets.only(right: 2.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_user_name".tr, style: theme.textTheme.bodySmall), SizedBox(height: 4.v), BlocSelector<CompleteYourProfileBloc, CompleteYourProfileState, TextEditingController?>(selector: (state) => state.userNameController, builder: (context, userNameController) {return CustomTextFormField(controller: userNameController, hintText: "lbl_lionelmessi10".tr, contentPadding: EdgeInsets.symmetric(horizontal: 10.h, vertical: 13.v));})])); } 
/// Section Widget
Widget _buildPhoneNumber(BuildContext context) { return Padding(padding: EdgeInsets.only(right: 2.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_phone_number".tr, style: theme.textTheme.bodySmall), SizedBox(height: 4.v), BlocBuilder<CompleteYourProfileBloc, CompleteYourProfileState>(builder: (context, state) {return CustomPhoneNumber(country: state.selectedCountry ?? CountryPickerUtils.getCountryByPhoneCode('1'), controller: state.phoneNumberController, onTap: (Country value) {context.read<CompleteYourProfileBloc>().add(ChangeCountryEvent(value: value));});})])); } 
/// Section Widget
Widget _buildGender(BuildContext context) { return Padding(padding: EdgeInsets.only(right: 2.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(left: 1.h), child: Text("lbl_gender".tr, style: theme.textTheme.bodySmall)), SizedBox(height: 4.v), BlocSelector<CompleteYourProfileBloc, CompleteYourProfileState, CompleteYourProfileModel?>(selector: (state) => state.completeYourProfileModelObj, builder: (context, completeYourProfileModelObj) {return CustomDropDown(hintText: "lbl_select".tr, hintStyle: CustomTextStyles.bodySmallBluegray90001, items: completeYourProfileModelObj?.dropdownItemList ?? [], contentPadding: EdgeInsets.symmetric(horizontal: 9.h, vertical: 13.v), borderDecoration: DropDownStyleHelper.outlineGray, onChanged: (value) {context.read<CompleteYourProfileBloc>().add(ChangeDropDownEvent(value: value));});})])); } 
/// Section Widget
Widget _buildCity(BuildContext context) { return Expanded(child: Padding(padding: EdgeInsets.only(right: 10.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(left: 4.h), child: Text("lbl_city".tr, style: theme.textTheme.bodySmall)), SizedBox(height: 3.v), CustomOutlinedButton(height: 44.v, width: 100.h, text: "lbl_alexandria".tr, buttonStyle: CustomButtonStyles.outlineGray, buttonTextStyle: CustomTextStyles.bodySmallBluegray90001)]))); } 
/// Section Widget
Widget _buildPostal(BuildContext context) { return Expanded(child: Padding(padding: EdgeInsets.only(left: 10.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(left: 3.h), child: Text("lbl_postal".tr, style: theme.textTheme.bodySmall)), SizedBox(height: 4.v), BlocSelector<CompleteYourProfileBloc, CompleteYourProfileState, TextEditingController?>(selector: (state) => state.zipcodeController, builder: (context, zipcodeController) {return CustomTextFormField(width: 100.h, controller: zipcodeController, hintText: "lbl_19519".tr, textInputAction: TextInputAction.done);})]))); } 
/// Section Widget
Widget _buildAlexandria(BuildContext context) { return Padding(padding: EdgeInsets.only(right: 2.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [_buildCity(context), Expanded(child: Padding(padding: EdgeInsets.symmetric(horizontal: 10.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(left: 4.h), child: Text("lbl_address".tr, style: theme.textTheme.bodySmall)), SizedBox(height: 4.v), BlocSelector<CompleteYourProfileBloc, CompleteYourProfileState, TextEditingController?>(selector: (state) => state.addressController, builder: (context, addressController) {return CustomTextFormField(width: 100.h, controller: addressController, hintText: "lbl_wardian".tr);})]))), _buildPostal(context)])); } 

/// Navigates to the previous screen.
onTapArrowLeft(BuildContext context) { NavigatorService.goBack(); } 
/// Navigates to the logInScreen when the action is triggered.
onTapCompleteProfile(BuildContext context) { NavigatorService.pushNamed(AppRoutes.logInScreen, ); } 
 }
