import 'bloc/sceond_bloc.dart';import 'models/sceond_model.dart';import 'package:clean_egypt/core/app_export.dart';import 'package:clean_egypt/widgets/app_bar/appbar_leading_iconbutton.dart';import 'package:clean_egypt/widgets/app_bar/appbar_subtitle_four.dart';import 'package:clean_egypt/widgets/app_bar/custom_app_bar.dart';import 'package:clean_egypt/widgets/custom_elevated_button.dart';import 'package:flutter/material.dart';class SceondScreen extends StatelessWidget {const SceondScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<SceondBloc>(create: (context) => SceondBloc(SceondState(sceondModelObj: SceondModel()))..add(SceondInitialEvent()), child: SceondScreen()); } 
@override Widget build(BuildContext context) { return BlocBuilder<SceondBloc, SceondState>(builder: (context, state) {return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 23.h, vertical: 20.v), child: Column(children: [Padding(padding: EdgeInsets.only(right: 1.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Container(width: 133.h, margin: EdgeInsets.only(left: 1.h), child: RichText(text: TextSpan(children: [TextSpan(text: "lbl_replace_the".tr, style: CustomTextStyles.titleLargeBlack90022_1), TextSpan(text: "lbl_garbage".tr, style: CustomTextStyles.titleLargePrimary)]), textAlign: TextAlign.left)), SizedBox(height: 10.v), Text("msg_to_earn_offers".tr, style: CustomTextStyles.titleSmallBlack900), SizedBox(height: 39.v), _buildReplaceTheGarbageTen(context)])), SizedBox(height: 30.v), CustomImageView(imagePath: ImageConstant.imgGrid, height: 7.v, width: 81.h), SizedBox(height: 83.v), CustomElevatedButton(text: "lbl_continue".tr, onPressed: () {onTapContinue(context);}), SizedBox(height: 5.v)]))));}); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 58.h, leading: AppbarLeadingIconbutton(margin: EdgeInsets.only(left: 26.h, top: 12.v, bottom: 12.v), onTap: () {onTapArrowDown(context);}), actions: [AppbarSubtitleFour(text: "lbl_skip".tr, margin: EdgeInsets.fromLTRB(33.h, 18.v, 33.h, 14.v))]); } 
/// Section Widget
Widget _buildReplaceTheGarbageTen(BuildContext context) { return Align(alignment: Alignment.center, child: Container(margin: EdgeInsets.only(left: 13.h, right: 8.h), padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 8.v), decoration: AppDecoration.fillGray.copyWith(borderRadius: BorderRadiusStyle.roundedBorder161), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.end, children: [SizedBox(height: 19.v), CustomImageView(imagePath: ImageConstant.imgMakeItRainCuate, height: 288.adaptSize, width: 288.adaptSize, radius: BorderRadius.circular(81.h))]))); } 
/// Navigates to the firstScreen when the action is triggered.
onTapArrowDown(BuildContext context) { NavigatorService.pushNamed(AppRoutes.firstScreen, ); } 
/// Navigates to the thirdScreen when the action is triggered.
onTapContinue(BuildContext context) { NavigatorService.pushNamed(AppRoutes.thirdScreen, ); } 
 }
