import 'bloc/settings_bloc.dart';import 'models/settings_model.dart';import 'package:clean_egypt/core/app_export.dart';import 'package:clean_egypt/widgets/app_bar/appbar_leading_iconbutton_one.dart';import 'package:clean_egypt/widgets/app_bar/appbar_subtitle_two.dart';import 'package:clean_egypt/widgets/app_bar/custom_app_bar.dart';import 'package:flutter/material.dart';class SettingsScreen extends StatelessWidget {const SettingsScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<SettingsBloc>(create: (context) => SettingsBloc(SettingsState(settingsModelObj: SettingsModel()))..add(SettingsInitialEvent()), child: SettingsScreen()); } 
@override Widget build(BuildContext context) { return BlocBuilder<SettingsBloc, SettingsState>(builder: (context, state) {return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 30.h, vertical: 27.v), child: Column(children: [_buildLockRow(context), SizedBox(height: 13.v), Divider(endIndent: 6.h), SizedBox(height: 15.v), _buildVectorRow(context), SizedBox(height: 13.v), Divider(endIndent: 6.h), SizedBox(height: 15.v), _buildDeleteAccountRow(context), SizedBox(height: 5.v)]))));}); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 65.h, leading: AppbarLeadingIconbuttonOne(imagePath: ImageConstant.imgArrowLeftGray900, margin: EdgeInsets.only(left: 25.h, top: 8.v, bottom: 8.v), onTap: () {onTapArrowLeft(context);}), centerTitle: true, title: AppbarSubtitleTwo(text: "lbl_settings".tr)); } 
/// Section Widget
Widget _buildLockRow(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 3.h, right: 12.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgLockBlueGray600, height: 23.v, width: 18.h, margin: EdgeInsets.only(bottom: 3.v)), Padding(padding: EdgeInsets.only(left: 14.h), child: Text("msg_notification_settings".tr, style: theme.textTheme.bodyLarge)), Spacer(), CustomImageView(imagePath: ImageConstant.imgArrowRightBlueGray600, height: 16.v, width: 10.h, margin: EdgeInsets.only(top: 4.v, bottom: 6.v))])); } 
/// Section Widget
Widget _buildVectorRow(BuildContext context) { return Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(right: 12.h), child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [SizedBox(height: 27.adaptSize, width: 27.adaptSize, child: Stack(alignment: Alignment.center, children: [Align(alignment: Alignment.topRight, child: Container(height: 2.adaptSize, width: 2.adaptSize, margin: EdgeInsets.only(top: 8.v, right: 7.h), decoration: BoxDecoration(color: appTheme.blueGray600, borderRadius: BorderRadius.circular(1.h)))), CustomImageView(imagePath: ImageConstant.imgUserBlueGray600, height: 27.adaptSize, width: 27.adaptSize, alignment: Alignment.center)])), Padding(padding: EdgeInsets.only(left: 8.h), child: Text("lbl_password_manger".tr, style: theme.textTheme.bodyLarge)), Spacer(), CustomImageView(imagePath: ImageConstant.imgArrowRightBlueGray600, height: 16.v, width: 10.h, margin: EdgeInsets.only(top: 5.v, bottom: 7.v))]))); } 
/// Section Widget
Widget _buildDeleteAccountRow(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 5.h, right: 12.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgThumbsUpBlueGray600, height: 22.v, width: 24.h, margin: EdgeInsets.only(top: 2.v)), Padding(padding: EdgeInsets.only(left: 10.h), child: Text("lbl_delete_account".tr, style: theme.textTheme.bodyLarge)), Spacer(), CustomImageView(imagePath: ImageConstant.imgArrowRightBlueGray600, height: 16.v, width: 10.h, margin: EdgeInsets.only(top: 5.v, bottom: 4.v))])); } 

/// Navigates to the previous screen.
onTapArrowLeft(BuildContext context) { NavigatorService.goBack(); } 
 }
