import 'bloc/location_access_bloc.dart';import 'models/location_access_model.dart';import 'package:clean_egypt/core/app_export.dart';import 'package:clean_egypt/widgets/app_bar/appbar_leading_iconbutton_one.dart';import 'package:clean_egypt/widgets/app_bar/appbar_subtitle_two.dart';import 'package:clean_egypt/widgets/app_bar/custom_app_bar.dart';import 'package:clean_egypt/widgets/custom_search_view.dart';import 'package:flutter/material.dart';class LocationAccessScreen extends StatelessWidget {const LocationAccessScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<LocationAccessBloc>(create: (context) => LocationAccessBloc(LocationAccessState(locationAccessModelObj: LocationAccessModel()))..add(LocationAccessInitialEvent()), child: LocationAccessScreen()); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 33.h, vertical: 7.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [BlocSelector<LocationAccessBloc, LocationAccessState, TextEditingController?>(selector: (state) => state.searchController, builder: (context, searchController) {return CustomSearchView(controller: searchController, hintText: "lbl_madinaty".tr, borderDecoration: SearchViewStyleHelper.outlineGray);}), SizedBox(height: 33.v), _buildSaveColumn(context), SizedBox(height: 14.v), Text("lbl_reach_result".tr, style: CustomTextStyles.labelLargeGray60001), SizedBox(height: 8.v), Row(children: [CustomImageView(imagePath: ImageConstant.imgSavePrimary, height: 18.adaptSize, width: 18.adaptSize, margin: EdgeInsets.only(top: 4.v, bottom: 1.v)), Padding(padding: EdgeInsets.only(left: 18.h), child: Text("lbl_wardian".tr, style: CustomTextStyles.bodyLargeBlack900))]), SizedBox(height: 5.v), Padding(padding: EdgeInsets.only(left: 4.h), child: Text("msg_hulk_vila_g3_villa32".tr, style: CustomTextStyles.bodyLargeGray600))])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 65.h, leading: AppbarLeadingIconbuttonOne(imagePath: ImageConstant.imgArrowLeftGray900, margin: EdgeInsets.only(left: 25.h, top: 8.v, bottom: 8.v), onTap: () {onTapArrowLeft(context);}), centerTitle: true, title: AppbarSubtitleTwo(text: "msg_enter_your_location".tr)); } 
/// Section Widget
Widget _buildSaveColumn(BuildContext context) { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Row(children: [CustomImageView(imagePath: ImageConstant.imgSavePrimary, height: 22.adaptSize, width: 22.adaptSize, margin: EdgeInsets.only(bottom: 2.v)), Padding(padding: EdgeInsets.only(left: 13.h), child: Text("msg_use_my_current_location".tr, style: CustomTextStyles.titleMediumBlack900Medium))]), SizedBox(height: 17.v), Divider()]); } 

/// Navigates to the previous screen.
onTapArrowLeft(BuildContext context) { NavigatorService.goBack(); } 
 }
