import 'bloc/refer_earn_bloc.dart';import 'models/refer_earn_model.dart';import 'package:clean_egypt/core/app_export.dart';import 'package:clean_egypt/widgets/custom_elevated_button.dart';import 'package:clean_egypt/widgets/custom_icon_button.dart';import 'package:clean_egypt/widgets/custom_outlined_button.dart';import 'package:flutter/material.dart';class ReferEarnScreen extends StatelessWidget {const ReferEarnScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<ReferEarnBloc>(create: (context) => ReferEarnBloc(ReferEarnState(referEarnModelObj: ReferEarnModel()))..add(ReferEarnInitialEvent()), child: ReferEarnScreen()); } 
@override Widget build(BuildContext context) { return BlocBuilder<ReferEarnBloc, ReferEarnState>(builder: (context, state) {return SafeArea(child: Scaffold(body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 17.h, vertical: 25.v), child: Column(children: [SizedBox(height: 484.v, width: 358.h, child: Stack(alignment: Alignment.topCenter, children: [Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 8.h), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.end, children: [Align(alignment: Alignment.centerLeft, child: Row(children: [CustomIconButton(height: 40.adaptSize, width: 40.adaptSize, padding: EdgeInsets.all(12.h), onTap: () {onTapBtnArrowLeft(context);}, child: CustomImageView(imagePath: ImageConstant.imgArrowLeftGray900)), Padding(padding: EdgeInsets.only(left: 83.h, top: 7.v, bottom: 8.v), child: Text("lbl_refer_earn".tr, style: theme.textTheme.titleMedium))])), SizedBox(height: 267.v), Container(height: 106.v, width: 102.h, margin: EdgeInsets.only(right: 13.h), child: Stack(alignment: Alignment.bottomRight, children: [CustomImageView(imagePath: ImageConstant.imgClockYellow600, height: 46.adaptSize, width: 46.adaptSize, alignment: Alignment.bottomCenter, margin: EdgeInsets.only(bottom: 14.v)), Align(alignment: Alignment.bottomRight, child: Padding(padding: EdgeInsets.only(right: 27.h), child: Text("lbl_5".tr, style: theme.textTheme.headlineSmall))), Align(alignment: Alignment.topCenter, child: SizedBox(width: 102.h, child: RichText(text: TextSpan(children: [TextSpan(text: "msg_invite_a_friend_and2".tr, style: theme.textTheme.titleSmall), TextSpan(text: " ")]), textAlign: TextAlign.center)))])), SizedBox(height: 1.v), Text("lbl_referal_code".tr, style: CustomTextStyles.titleLargeBluegray90001Medium), SizedBox(height: 1.v), CustomElevatedButton(height: 37.v, width: 126.h, text: "lbl_yhrdyk".tr, rightIcon: Container(margin: EdgeInsets.only(left: 10.h), child: CustomImageView(imagePath: ImageConstant.imgFolderBlueGray600, height: 11.adaptSize, width: 11.adaptSize)), buttonStyle: CustomButtonStyles.fillGray, buttonTextStyle: CustomTextStyles.labelLargeBlack90013)]))), CustomImageView(imagePath: ImageConstant.imgSendLink, height: 358.adaptSize, width: 358.adaptSize, alignment: Alignment.topCenter, margin: EdgeInsets.only(top: 8.v))])), Spacer(), CustomOutlinedButton(text: "msg_share_referal_link".tr, margin: EdgeInsets.only(left: 9.h, right: 7.h)), SizedBox(height: 15.v), CustomOutlinedButton(text: "lbl_view_earnings".tr, margin: EdgeInsets.symmetric(horizontal: 8.h), buttonStyle: CustomButtonStyles.outlinePrimary, onPressed: () {onTapViewEarnings(context);}), SizedBox(height: 36.v)]))));}); } 

/// Navigates to the previous screen.
onTapBtnArrowLeft(BuildContext context) { NavigatorService.goBack(); } 
/// Navigates to the viewEarningsScreen when the action is triggered.
onTapViewEarnings(BuildContext context) { NavigatorService.pushNamed(AppRoutes.viewEarningsScreen, ); } 
 }
