import 'bloc/remove_event_bloc.dart';import 'models/remove_event_model.dart';import 'package:clean_egypt/core/app_export.dart';import 'package:clean_egypt/widgets/custom_checkbox_button.dart';import 'package:clean_egypt/widgets/custom_icon_button.dart';import 'package:clean_egypt/widgets/custom_outlined_button.dart';import 'package:flutter/material.dart';class RemoveEventScreen extends StatelessWidget {const RemoveEventScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<RemoveEventBloc>(create: (context) => RemoveEventBloc(RemoveEventState(removeEventModelObj: RemoveEventModel()))..add(RemoveEventInitialEvent()), child: RemoveEventScreen()); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 10.v), child: Column(children: [SizedBox(height: 6.v), _buildPopupRow(context), SizedBox(height: 14.v), _buildDateColumn(context), SizedBox(height: 10.v), CustomImageView(imagePath: ImageConstant.imgBasemapImage, height: 221.v, width: 324.h), SizedBox(height: 18.v), Align(alignment: Alignment.centerLeft, child: GestureDetector(onTap: () {onTapYourAssigned(context);}, child: Padding(padding: EdgeInsets.only(left: 9.h), child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_see_all_your_assigned".tr, style: CustomTextStyles.bodyMediumTeal80001), CustomImageView(imagePath: ImageConstant.imgArrowLeft, height: 12.adaptSize, width: 12.adaptSize, margin: EdgeInsets.only(left: 4.h, top: 4.v, bottom: 6.v))]))))])), bottomNavigationBar: _buildRemoveEventButton(context))); } 
/// Section Widget
Widget _buildPopupRow(BuildContext context) { return Container(margin: EdgeInsets.symmetric(horizontal: 10.h), padding: EdgeInsets.symmetric(horizontal: 13.h, vertical: 8.v), decoration: AppDecoration.outlineBlack9001.copyWith(borderRadius: BorderRadiusStyle.roundedBorder5), child: Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.start, mainAxisSize: MainAxisSize.min, children: [Padding(padding: EdgeInsets.symmetric(vertical: 6.v), child: CustomIconButton(height: 35.adaptSize, width: 35.adaptSize, padding: EdgeInsets.all(6.h), decoration: IconButtonStyleHelper.outlineTeal, child: CustomImageView(imagePath: ImageConstant.imgCheckmarkGray10001))), Container(width: 181.h, margin: EdgeInsets.only(left: 6.h, top: 4.v), child: Text("msg_this_event_was_added".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: CustomTextStyles.titleSmallTeal80001SemiBold)), Spacer(), Padding(padding: EdgeInsets.only(bottom: 26.v), child: CustomIconButton(height: 21.adaptSize, width: 21.adaptSize, padding: EdgeInsets.all(6.h), decoration: IconButtonStyleHelper.fillTealTL10, child: CustomImageView(imagePath: ImageConstant.imgCloseWhiteA70001)))])); } 
/// Section Widget
Widget _buildDateColumn(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 9.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(left: 6.h), child: Text("msg_miami_beach_cleanup".tr, style: CustomTextStyles.titleMediumTeal8000118_1)), SizedBox(height: 6.v), CustomImageView(imagePath: ImageConstant.imgImage, height: 203.v, width: 324.h, radius: BorderRadius.circular(5.h), margin: EdgeInsets.only(left: 2.h)), SizedBox(height: 13.v), Padding(padding: EdgeInsets.only(left: 2.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(left: 2.h), child: BlocSelector<RemoveEventBloc, RemoveEventState, bool?>(selector: (state) => state.date, builder: (context, date) {return CustomCheckboxButton(text: "msg_february_14th_2023".tr, value: date, onChange: (value) {context.read<RemoveEventBloc>().add(ChangeCheckBoxEvent(value: value));});})), SizedBox(height: 6.v), Row(children: [CustomImageView(imagePath: ImageConstant.imgClock24x24, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.only(bottom: 1.v)), Padding(padding: EdgeInsets.only(left: 6.h, top: 2.v), child: Text("lbl_12pm_to_5pm".tr, style: CustomTextStyles.titleSmallBlack900SemiBold))])]), Card(clipBehavior: Clip.antiAlias, elevation: 0, margin: EdgeInsets.only(bottom: 5.v), shape: RoundedRectangleBorder(side: BorderSide(color: appTheme.gray20001, width: 6.h), borderRadius: BorderRadiusStyle.roundedBorder25), child: Container(height: 46.adaptSize, width: 46.adaptSize, decoration: AppDecoration.outlineGray20001.copyWith(borderRadius: BorderRadiusStyle.roundedBorder25), child: Stack(alignment: Alignment.center, children: [Align(alignment: Alignment.center, child: SizedBox(height: 46.adaptSize, width: 46.adaptSize, child: CircularProgressIndicator(value: 0.5, strokeWidth: 6.h))), Align(alignment: Alignment.center, child: Text("lbl_75".tr, style: CustomTextStyles.titleSmallManropeTeal80001ExtraBold))])))])), SizedBox(height: 8.v), Padding(padding: EdgeInsets.only(left: 2.h, right: 84.h), child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgLocation24x24, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.only(top: 10.v, bottom: 13.v)), Expanded(child: Container(width: 218.h, margin: EdgeInsets.only(left: 7.h), child: Text("msg_miami_beach_1_ocean".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: CustomTextStyles.titleSmallTeal80001)))]))])); } 
/// Section Widget
Widget _buildRemoveEventButton(BuildContext context) { return CustomOutlinedButton(text: "lbl_remove_event".tr, margin: EdgeInsets.only(left: 23.h, right: 27.h, bottom: 18.v), buttonStyle: CustomButtonStyles.outlineWhiteATL25, buttonTextStyle: CustomTextStyles.titleMediumPrimary18, onPressed: () {onTapRemoveEventButton(context);}); } 
/// Navigates to the favoriteScreen when the action is triggered.
onTapYourAssigned(BuildContext context) { NavigatorService.pushNamed(AppRoutes.favoriteScreen, ); } 
/// Navigates to the detailScreen when the action is triggered.
onTapRemoveEventButton(BuildContext context) { NavigatorService.pushNamed(AppRoutes.detailScreen, ); } 
 }
