import '../view_earnings_screen/widgets/userprofile_item_widget.dart';import 'bloc/view_earnings_bloc.dart';import 'models/userprofile_item_model.dart';import 'models/view_earnings_model.dart';import 'package:clean_egypt/core/app_export.dart';import 'package:clean_egypt/widgets/app_bar/appbar_leading_iconbutton_one.dart';import 'package:clean_egypt/widgets/app_bar/appbar_subtitle_two.dart';import 'package:clean_egypt/widgets/app_bar/custom_app_bar.dart';import 'package:clean_egypt/widgets/custom_outlined_button.dart';import 'package:flutter/material.dart';class ViewEarningsScreen extends StatelessWidget {const ViewEarningsScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<ViewEarningsBloc>(create: (context) => ViewEarningsBloc(ViewEarningsState(viewEarningsModelObj: ViewEarningsModel()))..add(ViewEarningsInitialEvent()), child: ViewEarningsScreen()); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 11.h, vertical: 16.v), child: Column(children: [Text("lbl_total_earnings".tr, style: CustomTextStyles.titleSmallBluegray90001), Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgStar1, height: 25.v, width: 28.h, margin: EdgeInsets.only(top: 4.v, bottom: 6.v)), Padding(padding: EdgeInsets.only(left: 5.h), child: Text("lbl_4875".tr, style: theme.textTheme.headlineSmall))]), SizedBox(height: 12.v), CustomOutlinedButton(height: 47.v, width: 99.h, text: "lbl_withdraw".tr, buttonTextStyle: CustomTextStyles.titleSmallGray10001), SizedBox(height: 12.v), _buildReferrals(context), SizedBox(height: 30.v), _buildYourInvites(context), SizedBox(height: 5.v)])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 65.h, leading: AppbarLeadingIconbuttonOne(imagePath: ImageConstant.imgArrowLeftGray900, margin: EdgeInsets.only(left: 25.h, top: 8.v, bottom: 8.v), onTap: () {onTapArrowLeft(context);}), centerTitle: true, title: AppbarSubtitleTwo(text: "msg_referral_earnings".tr)); } 
/// Section Widget
Widget _buildReferrals(BuildContext context) { return SizedBox(height: 73.v, width: 370.h, child: Stack(alignment: Alignment.centerLeft, children: [Align(alignment: Alignment.center, child: Container(padding: EdgeInsets.symmetric(horizontal: 23.h, vertical: 5.v), decoration: AppDecoration.outlineGray300.copyWith(borderRadius: BorderRadiusStyle.roundedBorder10), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.end, children: [Padding(padding: EdgeInsets.only(top: 4.v), child: Column(children: [Text("lbl_referrals".tr, style: CustomTextStyles.titleSmallOnPrimaryContainer), SizedBox(height: 2.v), Text("lbl_6".tr, style: CustomTextStyles.titleLargeBlack900Medium)])), Padding(padding: EdgeInsets.only(top: 4.v), child: Column(children: [Text("lbl_reward".tr, style: CustomTextStyles.titleSmallOnPrimaryContainer), SizedBox(height: 2.v), Text("lbl_5".tr, style: CustomTextStyles.titleLargeBlack900Medium)])), Padding(padding: EdgeInsets.only(top: 4.v), child: Column(children: [Text("lbl_pending".tr, style: CustomTextStyles.titleSmallOnPrimaryContainer), Text("lbl_3".tr, style: CustomTextStyles.titleLargeBlack900Medium)]))]))), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 121.h), child: SizedBox(height: 72.v, child: VerticalDivider(width: 1.h, thickness: 1.v, color: appTheme.gray300)))), Align(alignment: Alignment.centerRight, child: Padding(padding: EdgeInsets.only(right: 118.h), child: SizedBox(height: 72.v, child: VerticalDivider(width: 1.h, thickness: 1.v, color: appTheme.gray300))))])); } 
/// Section Widget
Widget _buildYourInvites(BuildContext context) { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_your_invites".tr, style: CustomTextStyles.labelLargeOnPrimaryContainer), SizedBox(height: 15.v), BlocSelector<ViewEarningsBloc, ViewEarningsState, ViewEarningsModel?>(selector: (state) => state.viewEarningsModelObj, builder: (context, viewEarningsModelObj) {return ListView.separated(physics: NeverScrollableScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: 16.v);}, itemCount: viewEarningsModelObj?.userprofileItemList.length ?? 0, itemBuilder: (context, index) {UserprofileItemModel model = viewEarningsModelObj?.userprofileItemList[index] ?? UserprofileItemModel(); return UserprofileItemWidget(model);});})]); } 

/// Navigates to the previous screen.
onTapArrowLeft(BuildContext context) { NavigatorService.goBack(); } 
 }
