import '../notification_screen/widgets/todaysection_item_widget.dart';import 'bloc/notification_bloc.dart';import 'models/notification_model.dart';import 'models/todaysection_item_model.dart';import 'package:clean_egypt/core/app_export.dart';import 'package:clean_egypt/widgets/app_bar/appbar_leading_iconbutton_one.dart';import 'package:clean_egypt/widgets/app_bar/appbar_subtitle_two.dart';import 'package:clean_egypt/widgets/app_bar/appbar_trailing_button.dart';import 'package:clean_egypt/widgets/app_bar/custom_app_bar.dart';import 'package:flutter/material.dart';import 'package:grouped_list/grouped_list.dart';class NotificationScreen extends StatelessWidget {const NotificationScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<NotificationBloc>(create: (context) => NotificationBloc(NotificationState(notificationModelObj: NotificationModel()))..add(NotificationInitialEvent()), child: NotificationScreen()); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Padding(padding: EdgeInsets.only(top: 20.v), child: BlocSelector<NotificationBloc, NotificationState, NotificationModel?>(selector: (state) => state.notificationModelObj, builder: (context, notificationModelObj) {return GroupedListView<TodaysectionItemModel, String>(shrinkWrap: true, stickyHeaderBackgroundColor: Colors.transparent, elements: notificationModelObj?.todaysectionItemList ?? [], groupBy: (element) => element.groupBy!, sort: false, groupSeparatorBuilder: (String value) {return Padding(padding: EdgeInsets.only(top: 31.v, bottom: 16.v), child: Column(children: [Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text(value, style: CustomTextStyles.bodyMediumGray50002.copyWith(color: appTheme.gray50002)), Text(value, style: CustomTextStyles.bodyMediumGreenA200.copyWith(color: appTheme.greenA200))])]));}, itemBuilder: (context, model) {return TodaysectionItemWidget(model);}, separator: SizedBox(height: 17.v));})))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 65.h, leading: AppbarLeadingIconbuttonOne(imagePath: ImageConstant.imgArrowLeftGray900, margin: EdgeInsets.only(left: 25.h, top: 8.v, bottom: 8.v), onTap: () {onTapArrowLeft(context);}), centerTitle: true, title: AppbarSubtitleTwo(text: "lbl_notification".tr), actions: [AppbarTrailingButton(margin: EdgeInsets.fromLTRB(14.h, 12.v, 14.h, 9.v))]); } 

/// Navigates to the previous screen.
onTapArrowLeft(BuildContext context) { NavigatorService.goBack(); } 
 }
