import 'bloc/change_password_bloc.dart';import 'models/change_password_model.dart';import 'package:clean_egypt/core/app_export.dart';import 'package:clean_egypt/widgets/app_bar/appbar_leading_iconbutton_one.dart';import 'package:clean_egypt/widgets/app_bar/appbar_subtitle_two.dart';import 'package:clean_egypt/widgets/app_bar/custom_app_bar.dart';import 'package:clean_egypt/widgets/custom_elevated_button.dart';import 'package:flutter/material.dart';class ChangePasswordScreen extends StatelessWidget {const ChangePasswordScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<ChangePasswordBloc>(create: (context) => ChangePasswordBloc(ChangePasswordState(changePasswordModelObj: ChangePasswordModel()))..add(ChangePasswordInitialEvent()), child: ChangePasswordScreen()); } 
@override Widget build(BuildContext context) { return BlocBuilder<ChangePasswordBloc, ChangePasswordState>(builder: (context, state) {return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 13.v), child: Column(children: [Padding(padding: EdgeInsets.only(left: 1.h), child: _buildNewPassword(context, newPassword: "lbl_creat_password".tr, hiddenATMNo: "msg".tr)), SizedBox(height: 11.v), Align(alignment: Alignment.centerRight, child: Text("msg_forget_password".tr, style: CustomTextStyles.labelLargePrimary)), SizedBox(height: 7.v), Padding(padding: EdgeInsets.only(left: 1.h), child: _buildNewPassword(context, newPassword: "lbl_new_password".tr, hiddenATMNo: "msg".tr)), SizedBox(height: 10.v), Padding(padding: EdgeInsets.only(left: 1.h), child: _buildNewPassword(context, newPassword: "msg_confirm_new_password".tr, hiddenATMNo: "msg".tr)), Spacer(), SizedBox(height: 47.v), CustomElevatedButton(text: "lbl_change_password".tr, buttonTextStyle: CustomTextStyles.titleMediumWhiteA7000118, onPressed: () {onTapChangePassword(context);})]))));}); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 65.h, leading: AppbarLeadingIconbuttonOne(imagePath: ImageConstant.imgArrowLeftGray900, margin: EdgeInsets.only(left: 25.h, top: 8.v, bottom: 8.v), onTap: () {onTapArrowLeft(context);}), centerTitle: true, title: AppbarSubtitleTwo(text: "lbl_settings".tr)); } 
/// Common widget
Widget _buildNewPassword(BuildContext context, {required String newPassword, required String hiddenATMNo, }) { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text(newPassword, style: theme.textTheme.bodySmall!.copyWith(color: appTheme.blueGray90001)), SizedBox(height: 6.v), Container(padding: EdgeInsets.symmetric(horizontal: 15.h, vertical: 8.v), decoration: AppDecoration.outlineGray400.copyWith(borderRadius: BorderRadiusStyle.roundedBorder10), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(bottom: 7.v), child: Text(hiddenATMNo, style: CustomTextStyles.bodySmallBluegray90001.copyWith(color: appTheme.blueGray90001.withOpacity(0.5)))), CustomImageView(imagePath: ImageConstant.imgEye, height: 12.v, width: 13.h, margin: EdgeInsets.only(top: 5.v, right: 3.h, bottom: 7.v))]))]); } 

/// Navigates to the previous screen.
onTapArrowLeft(BuildContext context) { NavigatorService.goBack(); } 
/// Navigates to the profileScreen when the action is triggered.
onTapChangePassword(BuildContext context) { NavigatorService.pushNamed(AppRoutes.profileScreen, ); } 
 }
