import 'bloc/third_bloc.dart';import 'models/third_model.dart';import 'package:clean_egypt/core/app_export.dart';import 'package:clean_egypt/widgets/app_bar/appbar_leading_iconbutton.dart';import 'package:clean_egypt/widgets/app_bar/custom_app_bar.dart';import 'package:clean_egypt/widgets/custom_elevated_button.dart';import 'package:flutter/material.dart';class ThirdScreen extends StatelessWidget {const ThirdScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<ThirdBloc>(create: (context) => ThirdBloc(ThirdState(thirdModelObj: ThirdModel()))..add(ThirdInitialEvent()), child: ThirdScreen()); } 
@override Widget build(BuildContext context) { return BlocBuilder<ThirdBloc, ThirdState>(builder: (context, state) {return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 25.h, vertical: 20.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Container(width: 163.h, margin: EdgeInsets.only(left: 4.h), child: RichText(text: TextSpan(children: [TextSpan(text: "lbl_we_are_here_to".tr, style: CustomTextStyles.titleLargeBlack90022_1), TextSpan(text: "lbl_start_together".tr, style: CustomTextStyles.titleLargePrimary)]), textAlign: TextAlign.left)), Container(width: 213.h, margin: EdgeInsets.only(left: 4.h), child: Text("msg_making_egypt_a_cleaner".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: CustomTextStyles.titleSmallBlack900)), SizedBox(height: 14.v), _buildViewStack(context), SizedBox(height: 30.v), Container(height: 7.v, width: 82.h, margin: EdgeInsets.only(left: 125.h), decoration: BoxDecoration(color: theme.colorScheme.primary, borderRadius: BorderRadius.circular(3.h))), SizedBox(height: 84.v), CustomElevatedButton(text: "lbl_get_start".tr, onPressed: () {onTapGetStart(context);}), SizedBox(height: 5.v)]))));}); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: double.maxFinite, leading: AppbarLeadingIconbutton(margin: EdgeInsets.fromLTRB(26.h, 12.v, 335.h, 12.v), onTap: () {onTapArrowDown(context);})); } 
/// Section Widget
Widget _buildViewStack(BuildContext context) { return Align(alignment: Alignment.center, child: SizedBox(height: 333.v, width: 323.h, child: Stack(alignment: Alignment.topCenter, children: [Align(alignment: Alignment.center, child: Container(height: 323.adaptSize, width: 323.adaptSize, decoration: BoxDecoration(color: appTheme.gray5003, borderRadius: BorderRadius.circular(161.h)))), CustomImageView(imagePath: ImageConstant.imgTeamSpiritCuate, height: 288.adaptSize, width: 288.adaptSize, alignment: Alignment.topCenter)]))); } 
/// Navigates to the sceondScreen when the action is triggered.
onTapArrowDown(BuildContext context) { NavigatorService.pushNamed(AppRoutes.sceondScreen, ); } 
/// Navigates to the logInScreen when the action is triggered.
onTapGetStart(BuildContext context) { NavigatorService.pushNamed(AppRoutes.logInScreen, ); } 
 }
