import 'bloc/delete_account_bloc.dart';import 'models/delete_account_model.dart';import 'package:clean_egypt/core/app_export.dart';import 'package:clean_egypt/widgets/app_bar/appbar_subtitle_one.dart';import 'package:clean_egypt/widgets/app_bar/custom_app_bar.dart';import 'package:clean_egypt/widgets/custom_elevated_button.dart';import 'package:clean_egypt/widgets/custom_pin_code_text_field.dart';import 'package:flutter/material.dart';class DeleteAccountScreen extends StatelessWidget {const DeleteAccountScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<DeleteAccountBloc>(create: (context) => DeleteAccountBloc(DeleteAccountState(deleteAccountModelObj: DeleteAccountModel()))..add(DeleteAccountInitialEvent()), child: DeleteAccountScreen()); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 15.h, vertical: 28.v), child: Column(children: [Container(width: 319.h, margin: EdgeInsets.only(left: 29.h, right: 13.h), child: RichText(text: TextSpan(children: [TextSpan(text: "msg_enter_the_code".tr, style: theme.textTheme.bodyLarge), TextSpan(text: "msg_797208_to_delete".tr, style: CustomTextStyles.titleMediumGreen400)]), textAlign: TextAlign.center)), SizedBox(height: 12.v), Text("msg_please_enter_code".tr, style: CustomTextStyles.bodyMediumGray7000113), SizedBox(height: 22.v), Padding(padding: EdgeInsets.only(left: 21.h), child: BlocSelector<DeleteAccountBloc, DeleteAccountState, TextEditingController?>(selector: (state) => state.otpController, builder: (context, otpController) {return CustomPinCodeTextField(context: context, controller: otpController, onChanged: (value) {otpController?.text = value;});})), SizedBox(height: 23.v), Divider(indent: 21.h, endIndent: 15.h), Spacer(), CustomElevatedButton(text: "lbl_delete_account".tr, margin: EdgeInsets.only(left: 11.h, right: 9.h), buttonTextStyle: CustomTextStyles.titleMediumWhiteA7000118, onPressed: () {onTapDeleteAccount(context);}), SizedBox(height: 15.v), CustomElevatedButton(text: "lbl_cancel".tr, margin: EdgeInsets.symmetric(horizontal: 10.h), buttonTextStyle: CustomTextStyles.titleMediumWhiteA7000118, onPressed: () {onTapCancel(context);}), SizedBox(height: 32.v)])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(centerTitle: true, title: AppbarSubtitleOne(text: "msg_enter_confirmation".tr)); } 
/// Navigates to the settingsScreen when the action is triggered.
onTapDeleteAccount(BuildContext context) { NavigatorService.pushNamed(AppRoutes.settingsScreen, ); } 
/// Navigates to the settingsScreen when the action is triggered.
onTapCancel(BuildContext context) { NavigatorService.pushNamed(AppRoutes.settingsScreen, ); } 
 }
