import 'bloc/detail_bloc.dart';import 'models/detail_model.dart';import 'package:clean_egypt/core/app_export.dart';import 'package:clean_egypt/widgets/app_bar/appbar_leading_iconbutton_one.dart';import 'package:clean_egypt/widgets/app_bar/appbar_subtitle.dart';import 'package:clean_egypt/widgets/app_bar/custom_app_bar.dart';import 'package:clean_egypt/widgets/custom_checkbox_button.dart';import 'package:clean_egypt/widgets/custom_outlined_button.dart';import 'package:flutter/material.dart';class DetailScreen extends StatelessWidget {const DetailScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<DetailBloc>(create: (context) => DetailBloc(DetailState(detailModelObj: DetailModel()))..add(DetailInitialEvent()), child: DetailScreen()); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: SizedBox(width: SizeUtils.width, child: SingleChildScrollView(padding: EdgeInsets.only(top: 25.v), child: Padding(padding: EdgeInsets.symmetric(horizontal: 23.h), child: Column(children: [_buildEventDetails(context), SizedBox(height: 10.v), CustomImageView(imagePath: ImageConstant.imgBasemapImage, height: 221.v, width: 324.h), SizedBox(height: 13.v), _buildJoinThisEvent(context)])))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 65.h, leading: AppbarLeadingIconbuttonOne(imagePath: ImageConstant.imgArrowLeftGray900, margin: EdgeInsets.only(left: 25.h, top: 8.v, bottom: 8.v), onTap: () {onTapArrowLeft(context);}), centerTitle: true, title: AppbarSubtitle(text: "lbl_event_details".tr)); } 
/// Section Widget
Widget _buildEventDetails(BuildContext context) { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(left: 16.h), child: Text("msg_miami_beach_cleanup".tr, style: CustomTextStyles.titleMediumTeal8000118_1)), SizedBox(height: 6.v), CustomImageView(imagePath: ImageConstant.imgImage, height: 203.v, width: 324.h, radius: BorderRadius.circular(5.h), alignment: Alignment.center), SizedBox(height: 13.v), Padding(padding: EdgeInsets.only(left: 13.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(left: 2.h), child: BlocSelector<DetailBloc, DetailState, bool?>(selector: (state) => state.date, builder: (context, date) {return CustomCheckboxButton(text: "msg_february_14th_2023".tr, value: date, onChange: (value) {context.read<DetailBloc>().add(ChangeCheckBoxEvent(value: value));});})), SizedBox(height: 6.v), Row(children: [CustomImageView(imagePath: ImageConstant.imgClock24x24, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.only(bottom: 1.v)), Padding(padding: EdgeInsets.only(left: 6.h, top: 2.v), child: Text("lbl_12pm_to_5pm".tr, style: CustomTextStyles.titleSmallBlack900SemiBold))])]), Card(clipBehavior: Clip.antiAlias, elevation: 0, margin: EdgeInsets.only(bottom: 5.v), shape: RoundedRectangleBorder(side: BorderSide(color: appTheme.gray20001, width: 6.h), borderRadius: BorderRadiusStyle.roundedBorder25), child: Container(height: 46.adaptSize, width: 46.adaptSize, decoration: AppDecoration.outlineGray20001.copyWith(borderRadius: BorderRadiusStyle.roundedBorder25), child: Stack(alignment: Alignment.center, children: [Align(alignment: Alignment.center, child: SizedBox(height: 46.adaptSize, width: 46.adaptSize, child: CircularProgressIndicator(value: 0.5, strokeWidth: 6.h))), Align(alignment: Alignment.center, child: Text("lbl_75".tr, style: CustomTextStyles.titleSmallTeal80001SemiBold14))])))])), SizedBox(height: 8.v), Padding(padding: EdgeInsets.only(left: 12.h, right: 84.h), child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgLocation24x24, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.only(top: 10.v, bottom: 13.v)), Expanded(child: Container(width: 218.h, margin: EdgeInsets.only(left: 7.h), child: Text("msg_miami_beach_1_ocean".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: CustomTextStyles.titleSmallTeal80001)))]))]); } 
/// Section Widget
Widget _buildJoinThisEvent(BuildContext context) { return SizedBox(height: 178.v, width: 342.h, child: Stack(alignment: Alignment.topCenter, children: [Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 13.h), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_about_the_event".tr, style: CustomTextStyles.titleMediumTeal8000118_1), SizedBox(height: 20.v), Row(crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgClothes, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.only(top: 11.v, bottom: 13.v)), Expanded(child: Container(width: 265.h, margin: EdgeInsets.only(left: 7.h), child: Text("msg_comfortable_clothes".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: CustomTextStyles.titleMediumManropeBlack900)))]), SizedBox(height: 15.v), Padding(padding: EdgeInsets.only(right: 54.h), child: Row(children: [CustomImageView(imagePath: ImageConstant.imgCutlery, height: 24.adaptSize, width: 24.adaptSize), Padding(padding: EdgeInsets.only(left: 7.h), child: Text("msg_we_offer_lunch_and".tr, textAlign: TextAlign.center, style: CustomTextStyles.titleMediumManropeBlack900))])), SizedBox(height: 19.v), Row(children: [CustomImageView(imagePath: ImageConstant.imgChristmasStar, height: 24.adaptSize, width: 24.adaptSize), Padding(padding: EdgeInsets.only(left: 7.h), child: Text("msg_no_experience_needed".tr, textAlign: TextAlign.center, style: CustomTextStyles.titleMediumManropeBlack900))])]))), CustomOutlinedButton(width: 342.h, text: "lbl_join_this_event".tr, margin: EdgeInsets.only(top: 38.v), onPressed: () {onTapJoinThisEvent(context);}, alignment: Alignment.topCenter)])); } 

/// Navigates to the previous screen.
onTapArrowLeft(BuildContext context) { NavigatorService.goBack(); } 
/// Navigates to the removeEventScreen when the action is triggered.
onTapJoinThisEvent(BuildContext context) { NavigatorService.pushNamed(AppRoutes.removeEventScreen, ); } 
 }
